language: python

matrix:
  include:
    - os: linux
      sudo: false
      python: 2.7
    - os: linux
      sudo: false
      python: 3.5
    - os: osx
      language: generic

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip2 install pyflakes pep8 coverage coveralls nose; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install pyflakes pep8 coverage coveralls nose; fi

script:
  - pyflakes .
  - pep8 .
  - nosetests
  - coveralls
