language: python

matrix:
  include:
    - os: linux
      sudo: false
      python: 2.7
    - os: linux
      sudo: false
      python: 3.5
    - os: osx
      language: generic

install:
  - pip install pyflakes pep8 coverage coveralls nose

script:
  - pyflakes .
  - pep8 .
  - nosetests
  - coveralls
