language: python

matrix:
  include:
    - os: linux
      sudo: false
      python: 2.7
      cache:
        directories: test/cache
    - os: linux
      sudo: false
      python: 3.2
      cache:
        directories: test/cache
    - os: linux
      sudo: false
      python: 3.5
      cache:
        directories: test/cache
    - os: osx
      language: generic

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install python; fi
  - pip install pyflakes
  - pip install pep8

script:
  - pyflakes .
  - pep8 .
  - ./test.sh
