version: 1.0.{build}

shallow_clone: true

environment:
  matrix:
  - Lua: lua 5.3
  - Lua: luajit 2.0

configuration:
  - vs
  - vs08_32
  - mingw

build_script:
  - PATH %CD%\here\bin;C:\mingw\bin;%PATH%
  - python hererocks.py here --%Lua% --luarocks ^^ --verbose --target=%Configuration%

test_script:
  - lua -v
  - luarocks --version
  - luarocks install lua-term 0.3
  - luarocks install busted
  - busted --version
