version: 1.0.{build}

shallow_clone: true

cache:
  - downloads

environment:
  matrix:
  - Lua: lua 5.3
    Python: 35-x64
  - Lua: luajit 2.0
    Python: 35-x64
  - Lua: lua 5.3
    Python: 27
  - Lua: luajit 2.0
    Python: 27

configuration:
  - vs
  - vs08_32
  - mingw

build_script:
  - PATH %CD%\here\bin;C:\mingw\bin;C:\python%Python%;%PATH%
  - python --version
  - python hererocks.py here --%Lua% --luarocks=latest --verbose --target=%Configuration% --downloads=downloads --no-git-cache

test_script:
  - lua -v
  - luarocks --version
  - luarocks install lua-term 0.3
  - luarocks install busted
  - busted --version
