version: 1.0.{build}

shallow_clone: true

cache:
  - downloads

environment:
  matrix:
  - Python: 35-x64
  - Python: 27

build_script:
  - PATH %CD%\here\bin;C:\mingw\bin;C:\python%Python%;C:\python%Python%\scripts;%PATH%
  - pip install pyflakes pep8 coverage coveralls nose

test_script:
  - pyflakes .
  - pep8 .
  - nosetests
  - coverage report
  - if not "%COVERALLS_REPO_TOKEN%"=="" coveralls
