version: 1.0.{build}

shallow_clone: true

environment:
  matrix:
  - LUA: "lua 5.1"
  - LUA: "lua 5.2"
  - LUA: "lua 5.3"
  - LUA: "luajit 2.0"

configuration:
- 2015

platform: x86

before_build: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"'

build_script: python hererocks.py here --%LUA% --luarocks ^^ --verbose

test_script:
  - PATH %CD%\here\bin;%PATH%
  - lua -v
  - luarocks --version
  - luarocks install lua-term 0.3
  - luarocks install busted
  - busted --version
